In [13]:
import torch

In [14]:
torch.empty(1)


tensor([-2.1960e-27])

In [15]:
torch.empty(2,3)

tensor([[-2.1960e-27,  4.5789e-41,  2.5214e-35],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [16]:
torch.empty(2,2,3)


tensor([[[2.5214e-35, 0.0000e+00, 2.5129e-35],
         [0.0000e+00, 1.0415e-11, 1.3665e+22]],

        [[2.7299e-06, 1.0720e-08, 1.6149e-07],
         [2.6662e-09, 5.4931e-05, 2.4965e-18]]])

In [17]:
torch.rand(2,2)

tensor([[0.3042, 0.7207],
        [0.6340, 0.6442]])

In [18]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [26]:
torch.ones(2,2).dtype

torch.float32

In [25]:
torch.ones(2,2,dtype=torch.int).dtype

torch.int32

In [27]:
torch.ones(2,2,dtype=torch.double).dtype

torch.float64

In [28]:
torch.ones(2,2,dtype=torch.float16).dtype


torch.float16

In [30]:
torch.ones(2,2,dtype=torch.double).size()

torch.Size([2, 2])

In [31]:
torch.tensor([2.5,0.1])

tensor([2.5000, 0.1000])

In [33]:
x1 = torch.rand(2,2)
x2 = torch.rand(2,2)
x3 = x1 + x2
x1,x2,x3

(tensor([[0.7933, 0.5295],
         [0.9711, 0.4831]]),
 tensor([[0.6063, 0.9171],
         [0.4877, 0.1455]]),
 tensor([[1.3996, 1.4466],
         [1.4588, 0.6286]]))