In [2]:
import torch
x = torch.empty(1)
print(x)

tensor([0.])


C:\Users\Dilshan\AppData\Local\Temp\ipykernel_1912\3265078073.py:2: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  x = torch.empty(1)


In [3]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.4490e-39]])


In [5]:
x = torch.empty(2, 2, 2, 3)
print(x)

tensor([[[[1.0000e+00, 0.0000e+00, 1.2127e+12],
          [8.6460e-43, 1.4013e-45, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[9.8091e-45, 0.0000e+00, 1.1210e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.4013e-45, 0.0000e+00]]]])


In [6]:
x = torch.rand(2, 2)
print(x)

tensor([[0.5990, 0.1716],
        [0.5713, 0.9459]])


In [7]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [13]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x.dtype); print(x.size())

torch.float16
torch.Size([2, 2])


In [14]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [17]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x); print(y)

z1 = x + y
z2 = torch.add(x, y)
print(z1); print(z2)

tensor([[0.4052, 0.8970],
        [0.6351, 0.3308]])
tensor([[0.9261, 0.3063],
        [0.6776, 0.4225]])
tensor([[1.3313, 1.2033],
        [1.3127, 0.7532]])
tensor([[1.3313, 1.2033],
        [1.3127, 0.7532]])


In [21]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
y.add_(x) #updates y by adding x
print(y)

tensor([[1.0845, 1.3419],
        [0.9491, 0.2668]])


In [22]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z1 = x - y
z2 = torch.sub(x, y)

print(z1)
print(z2)

tensor([[ 0.1485, -0.2678],
        [ 0.4324,  0.4269]])
tensor([[ 0.1485, -0.2678],
        [ 0.4324,  0.4269]])


In [23]:
z3 = x*y
z4 = torch.mul(x, y)
print(z3); print(z4)

tensor([[0.8079, 0.2224],
        [0.3345, 0.4568]])
tensor([[0.8079, 0.2224],
        [0.3345, 0.4568]])


In [25]:
z1 = x/y
z2 = torch.div(x, y)
print(z1); print(z2)


tensor([[1.1794, 0.5709],
        [2.0775, 1.8619]])
tensor([[1.1794, 0.5709],
        [2.0775, 1.8619]])


In [35]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) #1st column
print(x[0, :]) #1st row
print(x[1, 1]) #one item as tensor
print(x[1, 1].item()) #one item (not as tensor)

tensor([[0.1776, 0.5804, 0.5137],
        [0.1585, 0.9365, 0.8779],
        [0.6018, 0.3383, 0.4349],
        [0.9336, 0.1422, 0.6600],
        [0.0396, 0.8958, 0.0074]])
tensor([0.1776, 0.1585, 0.6018, 0.9336, 0.0396])
tensor([0.1776, 0.5804, 0.5137])
tensor(0.9365)
0.9364538788795471
